# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspu-hub-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod 
    traefik.ingress.kubernetes.io/router.middlewares: default-spa-fallback@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd
spec:
  ingressClassName: traefik 
  rules:
  - host: aspu-hub.ddns.net
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: aspu-api
            port:
              number: 80
      - path: /storage
        pathType: Prefix
        backend:
          service:
            name: aspu-api
            port:
              number: 80
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: aspu-web
            port:
              number: 80
      - path: /supervisor
        pathType: Prefix
        backend:
          service:
            name: aspu-web
            port:
              number: 80

      - path: /ask
        pathType: Prefix
        backend:
          service:
            name: aspu-assistant
            port:
              number: 80
      - path: /generate-questions
        pathType: Prefix
        backend:
          service:
            name: quiz-generator-service 
            port:
              number: 80

      - path: / 
        pathType: Prefix
        backend:
          service:
            name: aspu-frontend-service
            port:
              number: 80
  tls: 
  - hosts:
    - aspu-hub.ddns.net 
    secretName: aspu-hub-tls-secret 
                    
