apiVersion: v1
kind: Secret
metadata:
  name: db-mysql
  namespace: default
type: Opaque
data:
    username: YXNwdQ==
    password: YXNwdQ==
    MAIL_USERNAME: ZTNmYWE2NjM1MTljMTY=
    MAIL_PASSWORD: ZTNlZTdlMDY4MGIyYjU=

