apiVersion: v1
kind: Service
metadata:
  name: aspu-api
  namespace: default
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - name: http-api
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
