apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspu-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assistant
  template:
    metadata:
      labels:
        app: assistant
    spec:
      containers:
        - name: assistant
          image: bm106/aspu-ai-assistant:v1.0.3
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 4Gi
          env:
            - name: GOOGLE_API_KEY
              value: "AIzaSyBFDl77j5QT7A8YoAQKbVz42o_U1rzyjek"
