apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-storage-pvc 
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path 
