apiVersion: v1
kind: Service
metadata:
  name: aspu-web
  namespace: default
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
